<a href="https://colab.research.google.com/github/ClaudioRob/controle-acervo-biblioteca-ufrn/blob/main/acervo_emprestimo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import requests
import pandas as pd

In [60]:
# URL base do repositório no GitHub
api_url = "https://api.github.com/repos/FranciscoFoz/7_Days_of_Code_Alura-Python-Pandas/contents/Dia_1-Importando_dados/Datasets/dados_emprestimos"

In [61]:
# Obter a lista de arquivos no diretório
response = requests.get(api_url)
files = response.json()

In [62]:
# Dicionário para armazenar os DataFrames importados
dataframes = {}

In [63]:
# Filtrar e ler arquivos CSV
for file in files:
    if file['name'].endswith('.csv'):
        file_url = file['download_url']
        df = pd.read_csv(file_url)
        dataframes[file['name']] = df
        print(f"Sucesso ao importar {file['name']}")

Sucesso ao importar emprestimos-20101.csv
Sucesso ao importar emprestimos-20102.csv
Sucesso ao importar emprestimos-20111.csv
Sucesso ao importar emprestimos-20112.csv
Sucesso ao importar emprestimos-20121.csv
Sucesso ao importar emprestimos-20122.csv
Sucesso ao importar emprestimos-20131.csv
Sucesso ao importar emprestimos-20132.csv
Sucesso ao importar emprestimos-20141.csv
Sucesso ao importar emprestimos-20142.csv
Sucesso ao importar emprestimos-20151.csv
Sucesso ao importar emprestimos-20152.csv
Sucesso ao importar emprestimos-20161.csv
Sucesso ao importar emprestimos-20162.csv
Sucesso ao importar emprestimos-20171.csv
Sucesso ao importar emprestimos-20172.csv
Sucesso ao importar emprestimos-20181.csv
Sucesso ao importar emprestimos-20182.csv
Sucesso ao importar emprestimos-20191.csv
Sucesso ao importar emprestimos-20192.csv
Sucesso ao importar emprestimos-20201.csv

In [79]:
# Concatenar todos os DataFrames em um único DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)
combined_df.count()

id_emprestimo           2258018
codigo_barras           2258018
data_renovacao           972298
data_emprestimo         2258018
data_devolucao          2251547
matricula_ou_siape      2254848
tipo_vinculo_usuario    2258018
dtype: int64

In [80]:
# Totalizando registros no DataFrame
total_registros = len(combined_df)
print("Total de registros no DataFrame:", total_registros)

Total de registros no DataFrame: 2258018

In [81]:
# Exibir os primeiros registros do DataFrame concatenado para verificação
print("DataFrame concatenado:")
# print(combined_df.head())
df = pd.DataFrame(combined_df)
# Mostrar DataFrame
display(df.head(10))

DataFrame concatenado:

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
4,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
5,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
6,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
7,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
8,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO
9,709689,L157395,2010/01/19 15:59:26.447000000,2010/01/04 08:27:33.596000000,2010/02/03 13:06:43.125000000,2.009046e+09,ALUNO DE GRADUAÇÃO

In [ ]:
# Salvar o DataFrame concatenado em um arquivo CSV (opcional)
# combined_df.to_csv('combined_data.csv', index=False)